include:
  - project: 'salomemeca/ci-templates'
    file: 'build.yml'
    ref: 'main'
  - project: 'salomemeca/ci-templates'
    file: 'upload.yml'
    ref: 'main'
  - project: 'salomemeca/ci-templates'
    file: 'test.yml'
    ref: 'main'

stages: 
   - build
   - upload
   - test

build:
    extends: .build
    stage: build
    variables:
        BUILD_BASE_DIR: '$CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/$CI_CONCURRENT_ID/$CI_PROJECT_NAMESPACE'
        GIT_CLONE_PATH: '$BUILD_BASE_DIR/dev/$CI_PROJECT_NAME'
        YAMM_SOFTWARE_NAME: 'SALOMEMECA_MEDCONVERTER'

test:
    extends: .test
    stage: test
    variables:
        BUILD_BASE_DIR: '$CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/$CI_CONCURRENT_ID/$CI_PROJECT_NAMESPACE'
        GIT_CLONE_PATH: '$BUILD_BASE_DIR/dev/$CI_PROJECT_NAME'
        SALOME_TEST_LABEL: 'SMECA_MEDCONVERTER'

upload:
    extends: .upload
    stage: upload
    variables:
        BUILD_BASE_DIR: '$CI_BUILDS_DIR/$CI_RUNNER_SHORT_TOKEN/$CI_CONCURRENT_ID/$CI_PROJECT_NAMESPACE'
        GIT_CLONE_PATH: '$BUILD_BASE_DIR/dev/$CI_PROJECT_NAME'
