include:
  - project: 'salomemeca/ci-templates'
    file: smeca_main.yml
    ref: 'main'

variables:
    # RUNNER_TAGS: vm_s10_n1    #psm-ci-smeca-s10-285-d.cmp.retd.edf.fr
    RUNNER_TAGS: vm_s10_n2      #psm-ci-build-smeca-621-i.cmp.retd.edf.fr


stages:
   - build
   - container-singularity
   - test

build:
    extends: .smeca_build
    stage: build
    variables:
        YAMM_SOFTWARE_NAME: 'SALOMEMECA_MEDCONVERTER'

container-singularity:
    extends: .smeca_singularity
    stage: container-singularity

test:
    extends: .smeca_test
    stage: test
    variables:
        DISPLAY: ':1'
        SALOME_TEST_LABEL: 'SMECA_MEDCONVERTER'
