include:
  - project: 'salomemeca/ci-templates'
    file: 'smeca2022-v9.8-s9-docker.yml'
    ref: 'main'


variables:
    RUNNER_TAGS: smeca2022-s9-yamm
    # RUNNER_TAGS: smeca2022-s10-yamm

stages:
   - build
   - test

build:
    extends: .smeca_build
    stage: build
    variables:
        YAMM_SOFTWARE_NAME: 'SALOMEMECA_MEDCONVERTER'

test:
    extends: .smeca_test
    stage: test
    variables:
        DISPLAY: ':1'
        SALOME_TEST_LABEL: 'SMECA_MEDCONVERTER'
